/* autogenerated by Processing revision 1293 on 2024-04-04 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.Random;
// import java.util.HashMap;
// import java.util.ArrayList;
// import java.io.File;
// import java.io.BufferedReader;
// import java.io.PrintWriter;
// import java.io.InputStream;
// import java.io.OutputStream;
// import java.io.IOException;

import Sorting.*;

public class Project extends PApplet {
	private final int RANDOM_SEED = 0;

	private Random rand = new Random(RANDOM_SEED);
	private int visual_height = 340;
	private int ui_height = 500;
	
	private int w = 10;
	private Double[] arr;

	BogoSort<Double> bogo;


	public void settings(){
		width = 1200;
		height = visual_height + ui_height;
	}

	public void setup(){
		arr = new Double[width/w];
		for (int i = 0; i < arr.length; i++){
			arr[i] = rand.nextDouble(visual_height);
		}

		frameRate(60);

		bogo = new BogoSort<Double>();
		bogo.sorting(arr);
	}

	public void draw(){
		background(51);

		for(int i = 0; i < arr.length; i++){
			stroke(0);
			fill(255);
			rect(i*w, height - arr[i].floatValue(), w, arr[i].floatValue());
		}

		arr = bogo.next();

	}

	static public void main(String[] passedArgs) {
		String[] appletArgs = new String[] { "Project" };
		if (passedArgs != null) {
			PApplet.main(concat(appletArgs, passedArgs));
		} else {
			PApplet.main(appletArgs);
		}
	}
}
